# Generated by Django 5.0.2 on 2024-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_TO', '0003_task_line_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shift_name',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1),
        ),
    ]
